// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoJY5WdXlwbbh7QqXuhyu6DxUUysEVGrM',
    appId: '1:278876406126:web:47cf81158f863fabbd017f',
    messagingSenderId: '278876406126',
    projectId: 'weather-c864b',
    authDomain: 'weather-c864b.firebaseapp.com',
    storageBucket: 'weather-c864b.appspot.com',
    measurementId: 'G-2HDYK2KTG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSMBHWm01e6Npr0kNvz6sPUiSFrfEjBXY',
    appId: '1:278876406126:android:60636fc9bbcb1a95bd017f',
    messagingSenderId: '278876406126',
    projectId: 'weather-c864b',
    storageBucket: 'weather-c864b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjNA6_dr43sJjuMkY0Z0DMjqyyWA3htGY',
    appId: '1:278876406126:ios:e1921850d5bfea61bd017f',
    messagingSenderId: '278876406126',
    projectId: 'weather-c864b',
    storageBucket: 'weather-c864b.appspot.com',
    androidClientId: '278876406126-nssnb8iv3fbjhqoqejhfrna60lk0rd4m.apps.googleusercontent.com',
    iosClientId: '278876406126-3i84u463b23p5gvk1p7k1sq9tbfsm74s.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjNA6_dr43sJjuMkY0Z0DMjqyyWA3htGY',
    appId: '1:278876406126:ios:e1921850d5bfea61bd017f',
    messagingSenderId: '278876406126',
    projectId: 'weather-c864b',
    storageBucket: 'weather-c864b.appspot.com',
    androidClientId: '278876406126-nssnb8iv3fbjhqoqejhfrna60lk0rd4m.apps.googleusercontent.com',
    iosClientId: '278876406126-3i84u463b23p5gvk1p7k1sq9tbfsm74s.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );
}
